{"uuid": "f4a46587-37e2-4676-a79f-9beee35c1446", "children": ["6f20b47d-1a75-44fb-9ba5-1880da51cc87"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service chromedriver.exe unexpectedly exited. Status code was: 127\n\n", "trace": "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/tests_project/conftest.py\", line 20, in browser\n    browser = webdriver.Chrome(options=options, executable_path=CHROME_PATH)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 80, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 101, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 106, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 119, in assert_process_still_running\n    raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1681454014861, "stop": 1681454015524}], "start": 1681454014861, "stop": 1681454015576}