{"uuid": "929f010b-5c6c-4367-a3a0-f6c697ef83f7", "children": ["864cca6a-9e9f-4eb4-aadc-fae76a8d58b6"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.252:4444/wd/hub:4444/wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002271168DD80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\conftest.py\", line 38, in browser\n    driver = webdriver.Remote(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\user\\PycharmProjects\\TheFinalProject\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1681759776484, "stop": 1681759787349}], "start": 1681759776484, "stop": 1681759787624}