{"name": "test_user_cant_see_success_message", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127", "trace": "request = <SubRequest 'browser' for <Function test_user_cant_see_success_message>>\n\n    @pytest.fixture(scope='function')\n    def browser(request):\n        browser_name = request.config.getoption(\"browser_name\")\n        language = request.config.getoption(\"language\")\n        executor = request.config.getoption(\"--executor\")\n        if executor == \"local\":\n            if browser_name == 'chrome':\n                options = Options()\n                options.add_experimental_option('prefs', {'intl.accept_languages': language})\n                print('\\nstart browser for test..')\n>               browser = webdriver.Chrome(options=options)\n\nconftest.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:80: in __init__\n    super().__init__(\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__\n    self.service.start()\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7faaaea4b3d0>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127\n\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py:119: WebDriverException"}, "start": 1681763092915, "stop": 1681763092915, "uuid": "5067abe7-6fe3-400e-a1b8-668a8ea33ebb", "historyId": "f839820fadcc5418eef5369a1303f3f4", "testCaseId": "f42deca83e315331cfa07499b5afc458", "fullName": "test_product_page.TestUserAddToBasketFromProductPage#test_user_cant_see_success_message", "labels": [{"name": "tag", "value": "setup"}, {"name": "suite", "value": "test_product_page"}, {"name": "subSuite", "value": "TestUserAddToBasketFromProductPage"}, {"name": "host", "value": "38452a33324c"}, {"name": "thread", "value": "8-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_product_page"}]}