{"uuid": "6af5535e-59b4-49a3-86d8-752760ce0539", "children": ["0feefdfb-2c46-4440-aed5-dbd2523a837a"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127\n\n", "trace": "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/app/conftest.py\", line 24, in browser\n    browser = webdriver.Chrome(options=options)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 80, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 101, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 106, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 119, in assert_process_still_running\n    raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1681763078710, "stop": 1681763079359}], "start": 1681763078710, "stop": 1681763079397}