{"name": "test_message_disappeared_after_adding_product_to_basket", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127", "trace": "request = <SubRequest 'browser' for <Function test_message_disappeared_after_adding_product_to_basket>>\n\n    @pytest.fixture(scope='function')\n    def browser(request):\n        browser_name = request.config.getoption(\"browser_name\")\n        language = request.config.getoption(\"language\")\n        executor = request.config.getoption(\"--executor\")\n        if executor == \"local\":\n            if browser_name == 'chrome':\n                options = Options()\n                options.add_experimental_option('prefs', {'intl.accept_languages': language})\n                print('\\nstart browser for test..')\n>               browser = webdriver.Chrome(ChromeDriverManager().install(),options=options)\n\nconftest.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:80: in __init__\n    super().__init__(\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__\n    self.service.start()\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7fe17e7eae90>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127\n\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py:119: WebDriverException"}, "start": 1681762162943, "stop": 1681762162943, "uuid": "08812a24-400d-4154-b5b1-601c40f768cc", "historyId": "778151ff98c7d63a55ee1a4b3d28f6bc", "testCaseId": "3fca896906b6fc9a65e0fff73101183d", "fullName": "test_product_page#test_message_disappeared_after_adding_product_to_basket", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_product_page"}, {"name": "host", "value": "6204c0f9b44c"}, {"name": "thread", "value": "8-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_product_page"}]}