{"uuid": "8e057445-f99f-4a99-a93a-ef3c7927cf25", "children": ["fe9ab7d0-5601-412c-b53a-c5d71b908b1a"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127\n\n", "trace": "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/app/conftest.py\", line 24, in browser\n    browser = webdriver.Chrome(ChromeDriverManager().install(),options=options)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 80, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 101, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 106, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 119, in assert_process_still_running\n    raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1681761688716, "stop": 1681761689233}], "start": 1681761688716, "stop": 1681761689262}