{"uuid": "256403ef-b00c-4fdc-9bc0-bcb2507aca60", "children": ["4f3a1066-cae8-41d4-a326-2944e97ebc1c"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127\n\n", "trace": "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/app/conftest.py\", line 24, in browser\n    browser = webdriver.Chrome(ChromeDriverManager().install(),options=options)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 80, in __init__\n    super().__init__(\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 101, in __init__\n    self.service.start()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 106, in start\n    self.assert_process_still_running()\n  File \"/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 119, in assert_process_still_running\n    raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1681762165213, "stop": 1681762165729}], "start": 1681762165213, "stop": 1681762165760}