{"name": "test_quest_should_consist_word", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127", "trace": "request = <SubRequest 'browser' for <Function test_quest_should_consist_word>>\n\n    @pytest.fixture(scope='function')\n    def browser(request):\n        browser_name = request.config.getoption(\"browser_name\")\n        language = request.config.getoption(\"language\")\n        executor = request.config.getoption(\"--executor\")\n        if executor == \"local\":\n            if browser_name == 'chrome':\n                options = Options()\n                options.add_experimental_option('prefs', {'intl.accept_languages': language})\n                print('\\nstart browser for test..')\n>               browser = webdriver.Chrome(ChromeDriverManager().install(),options=options)\n\nconftest.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:80: in __init__\n    super().__init__(\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__\n    self.service.start()\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7feb479c5910>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self.path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/112.0.5615.49/chromedriver unexpectedly exited. Status code was: 127\n\n/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py:119: WebDriverException"}, "start": 1681761681048, "stop": 1681761681048, "uuid": "b60714fa-faff-448c-81af-6edb5fc35210", "historyId": "75cb10197f5411192a1dd4e783849c1b", "testCaseId": "ebf39fdbc92d2b0dad6b65a7b1796ebb", "fullName": "test_login_page#test_quest_should_consist_word", "labels": [{"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "f590dde632f3"}, {"name": "thread", "value": "8-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_page"}]}